int _putchar(char c);
void print_number(int n);
char *rot13(char *);
char *leet(char *);
void reverse_array(int *a, int n);
char *cap_string(char *);
char *_strcat(char *dest, char *src);
char *_strncpy(char *dest, char *src, int n);
char *string_toupper(char *);
int _strcmp(char *s1, char *s2);
char *_strncat(char *dest, char *src, int n);
